name:    declarative-tv-backend
version: "0.0.1"

dependencies:
- annotated-exception
- base >= 4.7 && < 5
- bytestring
- envy
- esqueleto
- exceptions
- file-embed
- http-types
- katip
- mtl
- persistent
- persistent-postgresql
- postgresql-simple
- resource-pool
- servant
- servant-server
- text
- time-manager
- transformers
- unliftio
- wai
- warp

default-extensions:
- DataKinds
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedRecordDot
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeOperators

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  declarative-tv-backend:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - declarative-tv-backend

# Test suite
tests:
  declarative-tv-backend-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - declarative-tv-backend
    - hspec
